--INSERT INTO USERS (VERSION, USERNAME, PASSWORD, EMAIL, RDATE, ROLE)
--VALUES (0, 'Bence', 'BenceKiraly00012', 'Bencehuszár000@gmail.com', '2018.04.19.', 'ADMIN');

--INSERT INTO FORUM(DESCRIPTION) VALUES ('memes');

INSERT INTO FORUM(VERSION, DESCRIPTION) VALUES (0, 'catalog');
--INSERT INTO FORUM(FORUMNAME, DESCRIPTION, CREATIONDATE, FORUMADMINID) VALUES ('Soros mafia', 'conspiracies', '1948.12.12.', 1);
--INSERT INTO FORUM(FORUMNAME, DESCRIPTION, CREATIONDATE, FORUMADMINID) VALUES ('Flatearth society', 'explore reality', '2015.12.12.', 2);
--INSERT INTO FORUM(FORUMNAME, DESCRIPTION, CREATIONDATE, FORUMADMINID) VALUES ('LuL', 'asdasdasdfsdffffffffff', '2011.12.12.', 12);