--INSERT INTO USERS (VERSION, USERNAME, PASSWORD, EMAIL, RDATE, ROLE)
--VALUES (0, 'Bence', 'BenceKiraly00012', 'Bencehuszár000@gmail.com', '2018.04.19.', 'ADMIN');




INSERT INTO FORUM(VERSION, FORUM_NAME, DESCRIPTION, CREATION_DATE, FORUM_ADMIN_ID) VALUES (0, 'Soros mafia', 'conspiracies', '1948.12.12.', 1);
INSERT INTO FORUM(VERSION, FORUM_NAME, DESCRIPTION, CREATION_DATE, FORUM_ADMIN_ID) VALUES (0, 'Flatearth society', 'explore reality', '2015.12.12.', 2);
INSERT INTO FORUM(VERSION, FORUM_NAME, DESCRIPTION, CREATION_DATE, FORUM_ADMIN_ID) VALUES (0, 'LuL', 'asdasdasdfsdffffffffff', '2011.12.12.', 12);